title: dWidgets
description: An application that shows and hides tools automatically
#repository: dsoutw/dWidgets-Android
show_downloads: false

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
